import { build } from 'esbuild';
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { blocks } from './content/seed.mjs';
const require = createRequire(import.meta.url);
const escape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/\0/g, '&#0;');
const attrs = (s) => escape(s).replace(/"/g, '&quot;');
const sourceBlock = (b) => `<script
  type="application/x-milo-source"
  id="${b.id}"
  data-kind="${b.kind}"
  data-name="${attrs(b.name)}"
  data-codec="amp-lt-v1">
${escape(b.text)}
</script>`;
const groups = [
  ['manifest', 'DOCUMENT SETTINGS', 'MILO SETTINGS'],
  ['slide', 'SLIDES', 'MILO SLIDES'],
  ['model', 'MODELS', 'MILO MODELS'],
  ['component', 'COMPONENTS', 'MILO COMPONENTS'],
  ['asset', 'ASSETS / LARGE EMBEDDED DATA', 'MILO ASSETS'],
];
const result = await build({
  entryPoints: ['src/app.ts'],
  bundle: true,
  write: false,
  metafile: true,
  format: 'iife',
  target: 'es2022',
  charset: 'utf8',
  minify: true,
  legalComments: 'eof',
});
const runtime = result.outputFiles[0].text;
if (/<\/script[\s>]/i.test(runtime)) throw new Error('Unsafe script terminator in runtime');
const katexRoot = resolve(dirname(require.resolve('katex/package.json')), 'dist');
let mathCSS = await readFile(resolve(katexRoot, 'katex.min.css'), 'utf8');
const fonts = [...mathCSS.matchAll(/src:([^;}]+)/g)];
for (const m of fonts) {
  const f = /url\((?:"|')?([^)'"\s]+\.woff2)(?:"|')?\)/.exec(m[1]);
  if (f) {
    const bytes = await readFile(resolve(katexRoot, f[1]));
    mathCSS = mathCSS.replace(
      m[0],
      `src:url(data:font/woff2;base64,${bytes.toString('base64')}) format("woff2")`,
    );
  }
}
if (/url\((?!data:)/.test(mathCSS)) throw new Error('Unembedded font dependency');
const css = await readFile('src/style.css', 'utf8');
const packages = [
  ...new Set(
    Object.keys(result.metafile.inputs)
      .filter((p) => p.startsWith('node_modules/'))
      .map((p) => {
        const a = p.split('/');
        return a.slice(0, a[1].startsWith('@') ? 3 : 2).join('/');
      }),
  ),
].sort();
let notices = 'Third-party software embedded in milo\n\n';
for (const root of packages) {
  const info = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'));
  let license = '';
  for (const name of (await readdir(root))
    .filter((n) => /^(?:licen[sc]e|copying)(?:[._-]|$)/i.test(n))
    .sort()) {
    try {
      license = await readFile(resolve(root, name), 'utf8');
      break;
    } catch {}
  }
  if (!license) throw new Error(`Missing dependency license: ${root}`);
  notices += `${info.name} ${info.version}\n${'='.repeat(60)}\n${license}\n\n`;
}
await writeFile('THIRD_PARTY_NOTICES.txt', notices);
const sources = groups
  .map(
    ([kind, title, marker]) => `<!-- ==================== ${title} ==================== -->

${blocks
  .filter((b) => b.kind === kind)
  .map(sourceBlock)
  .join('\n\n')}

<!-- END ${marker} -->`,
  )
  .join('\n\n');
const html = `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="milo" content="1">
<meta name="milo-id" content="milo-research-20260916">
<meta name="milo-runtime" content="0.1.0">
<title>小さな実験室 — milo</title>
<meta name="description" content="原稿・数式・動く図・編集道具を内蔵する、自己編集可能な単一HTML。">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%23205746'/%3E%3Cpath d='M8 7h7v18H8zm10 0h6v18h-6z' fill='%23c7dd9b'/%3E%3C/svg%3E">

<!-- ========================================================================
     MILO TOOLBOX
     Generated by build.mjs. Document edits leave this section unchanged.
     ======================================================================== -->
<!-- EMBEDDED DEPENDENCY: KaTeX CSS and WOFF2 fonts. Changed only on a runtime upgrade. -->
<style id="math-styles">${mathCSS}</style>
<!-- APPLICATION STYLE -->
<style id="app-styles">${css}</style>
<!-- APPLICATION RUNTIME: defined here, started after the document sources. -->
<script id="milo-runtime">globalThis.__bootMilo=()=>{
${runtime}
};</script>
<!-- END MILO TOOLBOX -->
</head>
<body>
<div id="app"></div>
<noscript>この文書を表示・編集するにはJavaScriptを有効にしてください。原稿はHTML内の MILO SOURCES にあります。</noscript>

<!-- ========================================================================
     MILO DOCUMENT
     Editable originals. These blocks, rather than rendered DOM, are saved.
     Codec amp-lt-v1: & becomes &amp;, < becomes &lt;, NUL becomes &#0;.
     ======================================================================== -->
${sources}

<!-- END MILO SOURCES -->
<!-- END MILO DOCUMENT -->

<!-- The toolbox starts only after every editable source block has been parsed. -->
<script id="milo-launcher">globalThis.__bootMilo();delete globalThis.__bootMilo;</script>
</body>
</html>
`;
await mkdir('dist', { recursive: true });
await writeFile('dist/milo.html', html);
console.log(
  `Built dist/milo.html: ${(Buffer.byteLength(html) / 1024).toFixed(0)} KiB; ${blocks.length} source blocks; all fonts embedded.`,
);
